version: "1"

capabilities:
  - contract_id: "abesh:httpclient"
    values:
      url: "https://jsonip.com"

  - contract_id: "abesh:httpserver"
    values:
      host: "0.0.0.0"
      port: "9090"
      default_request_timeout: "5s"
      default_content_type: "application/text"
      default_404_handler_enabled: "true"
      s500m: "500 error"
      s404m: "404 error"
      s403m: "403 error"
      s405m: "405 error"
      s408m: "408 request timeout"
      s499m: "499 request cancelled"

  - contract_id: "abesh:ex_authorizer"

  - contract_id: "abesh:ex_event_consumer"

  - contract_id: "abesh:ex_echo"
    values:
      key1: "test1"
      key2: "test2"

  - contract_id: "abesh:ex_err"

triggers:
  - trigger: "abesh:httpserver"
    service: "abesh:ex_echo"
    trigger_values:
      method: "GET"
      path: "/default"
    authrizer: "abesh:ex_authorizer"
    authorizer_expressin: "allowAll"

  - trigger: "abesh:httpserver"
    service: "abesh:ex_echo"
    trigger_values:
      method: "GET"
      path: "/echo"
    authrizer: "abesh:ex_authorizer"
    authorizer_expressin: "denyAll"

  - trigger: "abesh:httpserver"
    service: "abesh:ex_httpclient"
    trigger_values:
      method: "GET"
      path: "/httpclient"

  - trigger: "abesh:httpserver"
    service: "abesh:ex_err"
    trigger_values:
      method: "GET"
      path: "/err"

rpcs:
  - rpc: "abesh:ex_rpc"
    authorizer: "abesh:ex_authorizer"
    authorizer_expression: "allowAll"
    method: "/test.TestRPC/Add"

consumers:
  - source: "abesh:ex_echo"
    sink: "abesh:ex_event_consumer"

start:
  - "abesh:httpserver"
